version: "3"
services:
  database-rol:
    build:
      context: ./database
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - ./database/data:/var/lib/mysql
    restart: always
  php-http-rol:
    build:
      context: ../
      dockerfile: ./docker/php-apache/Dockerfile
      args:
        MAIN_DOMAIN: '${MAIN_DOMAIN}'
        ALL_DOMAINS: '${ALL_DOMAINS}'
        PROJECT_FOLDER_NAME: '${PROJECT_FOLDER_NAME}'
        WEBSITE_USER_PASSWORD: '${WEBSITE_USER_PASSWORD}'
        EMAIL: '${EMAIL}'
        EMAIL_PASSWORD: '${EMAIL_PASSWORD}'
        MYSQL_DATABASE: '${MYSQL_DATABASE}'
        MYSQL_USER: '${MYSQL_USER}'
        MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
        GENERATE_JS_ROUTES: '${GENERATE_JS_ROUTES}'
        I_WANT_MAILSERVER: '${I_WANT_MAILSERVER}'
    depends_on:
      - database-rol
      - mailserver-rol
    volumes:
      - ./apachelogs:/var/log/apache2
      - ./apachelogs/auth.log:/var/log/auth.log
      - './symfonylogs:/var/www/html/${PROJECT_FOLDER_NAME}/var/log/'
    labels:
      - traefik.http.routers.php-http.tls=true
      - traefik.http.routers.php-http.tls.certresolver=letsencrypt
      - traefik.http.services.php-http.loadbalancer.server.port=80
      - traefik.enable=true
      - traefik.http.routers.php-http.rule=Host(`remoteorlame.com`) && (PathPrefix(`/api`)
      - 'traefik.http.routers.php-http.tls.domains[0].main=remoteorlame.com'
    restart: always
  mailserver-rol:
    build:
      context: ./mailserver
    environment:
      EMAIL: '${EMAIL}'
      EMAIL_PASSWORD: '${EMAIL_PASSWORD}'
    container_name: mailserver-rol
    hostname: '${MAIN_DOMAIN}'
    env_file: mailserver.env
    volumes:
      - ./maildata/dms/mail-data/:/var/mail/
      - ./maildata/dms/mail-state/:/var/mail-state/
      - ./maildata/dms/mail-logs/:/var/log/mail/
      - ./maildata/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./certs/:/etc/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.routers.smtp.service=smtp"
      - "traefik.tcp.services.smtp.loadbalancer.server.port=25"
      - "traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.smtp-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp-ssl.tls=false"
      - "traefik.tcp.routers.smtp-ssl.entrypoints=smtp-ssl"
      - "traefik.tcp.routers.smtp-ssl.service=smtp-ssl"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.server.port=465"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.imap-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.imap-ssl.entrypoints=imap-ssl"
      - "traefik.tcp.routers.imap-ssl.service=imap-ssl"
      - "traefik.tcp.services.imap-ssl.loadbalancer.server.port=10993"
      - "traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2"
      - "traefik.tcp.routers.sieve.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sieve.entrypoints=sieve"
      - "traefik.tcp.routers.sieve.service=sieve"
      - "traefik.tcp.services.sieve.loadbalancer.server.port=4190"
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0